//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class Admin extends Uzytkownik {
	public Admin(String login, String haslo) {
		super(login, haslo);
	}
}
