//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//


import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class Kurs {
	private String id;
	private String tytul;
	private String haslo;
	private ArrayList<Uzytkownik> uzytkownicy;
	private ArrayList<Material> materialy;
	private ArrayList<Test> testy;
	private String sylabus;
	private boolean widocznosc;
	public Kurs(String id, String tytul, String haslo) {
		this.id = id;
		this.tytul = tytul;
		this.haslo = haslo;
		this.widocznosc = false;
	}
	
	public void zmienHaslo(String haslo) {
		try {
			MessageDigest digest = MessageDigest.getInstance("SHA-256");
			byte[] hash = digest.digest(haslo.getBytes(StandardCharsets.UTF_8));

			StringBuilder hexString = new StringBuilder();
			for (byte b : hash) {
				String hex = Integer.toHexString(0xff & b);
				if (hex.length() == 1) {
					hexString.append('0');
				}
				hexString.append(hex);
			}
			this.haslo = hexString.toString();

		} catch (Exception e) {
			throw new RuntimeException("Blad: ", e);
		}
	}
	
	public void dodajMaterialy(String plik, String tytul) {
		this.materialy.add(new Material(plik,tytul));
	}
	
	public void usunMaterialy(String tytul) {
        materialy.removeIf(material -> material.getTytul().equals(tytul));
	}
	
	public void wyswietlMaterialy() {
		for (Material material: this.materialy) {
			String path = material.getPlik();

			System.out.println("Plik: " + path);

			try {
				List<String> linie = Files.readAllLines(Path.of(path));
				for (String linia : linie) {
					System.out.println(linia);
				}

			} catch (IOException e) {
				System.out.println("Błąd w odczytywaniu pliku: " + path);
			}

			System.out.println();
		}
	}
	
	public void dodajTest(String plik, String tytul, LocalDate datakonca) {
		this.testy.add(new Test(plik,tytul,datakonca));
	}
	
	public void ocenTest(String nazwaTestu,String login, Float ocena) {
		for (Test test: testy) {
			if (test.getTytul().equals(nazwaTestu)) {
				test.ocen(login,ocena);
			}
		}
	}
	
	public void wyswietlTesty() {
		for (Test test: this.testy) {
			String path = test.getPlik();

			System.out.println("Plik: " + path);

			try {
				List<String> linie = Files.readAllLines(Path.of(path));
				for (String linia : linie) {
					System.out.println(linia);
				}

			} catch (IOException e) {
				System.out.println("Błąd w odczytywaniu pliku: " + path);
			}

			System.out.println();
		}
	}
	
	public void zmienWidocznoscKursu() {
		this.widocznosc = !widocznosc;
	}
	
	public void setSylabus(String plik) {
		this.sylabus = plik;
	}

	public String getId() {
		return this.id;
	}
}
