//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//


import java.util.ArrayList;
import java.util.List;

public class Student extends Uzytkownik {
	private ArrayList<Kurs> kursy;

	public Student(String login, String haslo) {
		super(login, haslo);
		this.kursy = new ArrayList<>();
	}

	public List<Kurs> getKursy() {
		return kursy;
	}
}
