//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//


import java.util.ArrayList;

public class Student extends Uzytkownik {
	private ArrayList<Kurs> kursy;

	public Student(String login) {
		super(login);
	}
	
	public void wybierzObecnyKurs(int id) {
	
	}
	
	public void dolaczDoKursu(int id) {
	
	}
	
	public void wyslijRozwiazanieDoTestu(String odp) {
	
	}
	
	public void sprawdzOceneTestu(String tytul) {
	
	}
	
	public void sprawdzMaterialy() {
	
	}
	
	public void sprawdzTesty() {
	
	}
	
	public void sprawdzSylabus() {
	
	}
}
