//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SystemZarzadzania.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//


import java.time.LocalDate;
import java.util.ArrayList;

public class SystemZarzadzania {
	private ArrayList<Kurs> kursy;
	private ArrayList<Uzytkownik> uzytkownicy;
	private Kurs obecnyKurs;
	private BazaLogowan bazaLogowan;
	public void SystemZarzadzania() {
		this.kursy = new ArrayList<>();
		this.uzytkownicy = new ArrayList<>();
	}
	
	public void zmienHasloDoKursu() {

	}
	
	public void dodajMaterialy(String plik, String tytul) {
		this.obecnyKurs.dodajMaterialy(plik,tytul);
	}
	
	public void usunMaterialy(String tytul) {
		this.obecnyKurs.usunMaterialy(tytul);
	}
	
	public void wyswietlMaterialy() {
		this.obecnyKurs.wyswietlMaterialy();
	}
	
	public void dodajTest(String plik, String tytul, LocalDate datakonca) {
		this.obecnyKurs.dodajTest(plik,tytul,datakonca);
	}
	
	public void ocenTest(String nazwa, String login, Float ocena) {
		this.obecnyKurs.ocenTest(nazwa,login,ocena);
	}
	
	public void wyswietlTesty() {
		this.obecnyKurs.wyswietlTesty();
	}
	
	public void zmienWidocznoscKursu() {
		this.obecnyKurs.zmienWidocznoscKursu();
	}
	
	public void setSylabus(String plik) {
		this.obecnyKurs.setSylabus(plik);
	}
	public void wyswietlKurs() {
		//wyswietl wszystko
	}
	public void zmienKurs(String id) {
		for (Kurs k: kursy) {
			if (k.getId().equals(id)) this.obecnyKurs = k;
		}
	}
}
