//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class Uzytkownik {
	private String login;
	private String haslo;
	private int id;
	public Uzytkownik(String login, String haslo) {
		this.login = login;
		this.haslo = haslo;
	}

    public String getLogin() {
        return login;
    }
}
