//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//


import java.time.LocalDate;
import java.util.ArrayList;

public class Wykladowca extends Uzytkownik {
	private ArrayList<Kurs> kursy;

	public Wykladowca(String login) {
		super(login);
	}
	
	public void utworzKurs(String nazwa, String haslo) {
	
	}
	
	public void zmienSylabus(String link) {
	
	}
	
	public void dodajMaterialy(String plik, String tytul) {
	
	}
	
	public void usunMaterialy(String plik) {
	
	}
	
	public void sprawdzMaterialy() {
	
	}
	
	public void dodajTest(String plik, String tytul, LocalDate datakonca) {
	
	}
	
	public void sprawdzOceny() {
	
	}
	
	public void sprawdzSylabus() {
	
	}
}
